### ISSUE TITLE
How to cookie on nextjs?

### ISSUE THREAD

**Issue by Qurus** [ivandotv/nextjs-translation-demo#14]
Hello I have followed tutorial but when I change the language on other page again reloading default language. How can I add cookies to keep switched language?

Thanks.

**Comment by ivandotv** [comment]
You can set the cookie when you switch the language, something like this:
```ts
 // Switcher.tsx
  import Cookies from 'js-cookie'
  function handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
    const locale = event.target.value as LOCALES

    setLocale(locale)
    router.push(router.pathname, router.pathname, { locale })

    // set the cookie
    Cookies.set('NEXT_LOCALE', locale, {
      expires: 31, //one month,
      path: '/',
      sameSite: 'lax'
    })
  }
```

**Comment by Qurus** [comment]
Well this is working only on index page on other pages again redirecting to default language. :(

**Comment by ivandotv** [comment]
That is the limitation of of the  Next.js framework. It only works on the index page.
You can read more about it in the [docs](https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie)
