### ISSUE TITLE
Infinite loop bug

### ISSUE THREAD

**Issue by reuixiy** [ivandotv/nextjs-translation-demo#8]
This demo is truely helpful! Since I'm working on a project using Next.js with LinguiJS which requires SSR, and I just get stucked.

I was going to replace LinguiJS with next-i18next, but thanks to your demo and guide, I think I will stick with LinguiJS!

However, I found a bug in this demo, router got infinite loop after you switch to another language and go back.

https://github.com/ivandotv/nextjs-translation-demo/blob/7ec34a038044d65c343ac8811a243ad353d32449/src/components/Switcher.tsx#L24-L28

https://github.com/ivandotv/nextjs-translation-demo/blob/7ec34a038044d65c343ac8811a243ad353d32449/src/components/Switcher.tsx#L33

Perhaps it's better if we push new route inside `onChange` handler directly, so that router change won't triger another router change and so on...

Thanks again!

**Comment by ivandotv** [comment]
Great catch!
Do you want to make a pull request?
